// Generated by scripts/configure — do not edit by hand.
// Bridges the SDD runtime Go binary (ospec-hooks) into opencode plugin events,
// because opencode has no shell-command hooks. See the generator's
// scripts/lib/target-profiles/opencode-plugin.js for rationale.
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const isWin = process.platform === "win32";
const EXE = isWin ? ".exe" : "";

function resolveBinary() {
  // Priority 1: known dist path produced by the CI build step.
  const distBin = resolve(join(here, "..", "..", "release", "dist", "ospec-hooks" + EXE));
  if (existsSync(distBin)) {
    return distBin;
  }
  // Priority 2: ospec-hooks on $PATH (developer environments with global install).
  return "ospec-hooks" + EXE;
}

export const OspecWorkflowPlugin = async ({ directory }) => {
  return {
    event: async ({ event }) => {
      if (event && event.type === "session.created") {
        try {
          const bin = resolveBinary();
          spawnSync(bin, ["session-start"], {
            input: JSON.stringify({ cwd: directory }),
            encoding: "utf8",
            shell: false,
          });
        } catch {
          // session-start is best-effort; never block a session on cache build.
        }
      }
    },
    "tool.execute.before": async (input, output) => {
      let verdict = null;
      try {
        const bin = resolveBinary();
        const result = spawnSync(bin, ["pre-tool-use"], {
          input: JSON.stringify({
            tool_name: input && input.tool,
            tool_input: (output && output.args) || {},
          }),
          encoding: "utf8",
          shell: false,
        });
        // Fail-open: binary absent, non-zero exit, or unparseable stdout -> allow.
        if (!result.error && result.status === 0 && result.stdout) {
          const parsed = JSON.parse(result.stdout);
          verdict = parsed && parsed.hookSpecificOutput;
        }
      } catch {
        // spawnSync or JSON.parse error -> fail-open (allow the tool call).
      }
      if (!verdict) {
        return;
      }
      // opencode plugins can only allow (return) or block (throw) — no native ask.
      if (verdict.permissionDecision === "deny" || verdict.permissionDecision === "ask") {
        throw new Error(verdict.permissionDecisionReason);
      }
    },
  };
};
