"use strict";

/**
 * Phase 8.1 — Verify that the branch-before-code text from Phase 7 is propagated
 * into every configured target via `scripts/configure`.
 *
 * This test is self-contained: `dist/` is gitignored and therefore absent on a
 * fresh checkout (CI). Instead of reading a pre-populated `ROOT/dist`, it
 * generates each target into a temp dir using the same `cli.js` path `check.js`
 * uses, then asserts the key phrases appear in the generated output.
 */

const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const test = require("node:test");
const { before, after } = require("node:test");

const ROOT = path.resolve(__dirname, "..");

/** The four configured targets generated by `scripts/configure/cli.js`. */
const TARGETS = ["claude", "vscode", "github-copilot", "opencode"];

/**
 * Key phrases from the Phase 7 edits that MUST appear in the generated output of
 * each target after `scripts/configure` runs.
 */
const BRANCH_PR_PHRASE = "Feature branch MUST be created before any project file is edited";
const ORCHESTRATOR_PHRASE = "RECOMIENDA confirmar que hay una rama de feature activa";

/** Generated temp output dir per target, populated in before(). */
const generated = new Map();

/** Generate a single target into a fresh temp dir and return its path. */
function generateTarget(target) {
  const outDir = fs.mkdtempSync(path.join(os.tmpdir(), `ospec-cfgtest-${target}-`));
  const result = spawnSync(
    process.execPath,
    ["scripts/configure/cli.js", "--target", target, "--source", ROOT, "--out", outDir, "--no-validate"],
    { cwd: ROOT, encoding: "utf8" }
  );
  if (result.status !== 0) {
    throw new Error(`configure cli failed for target ${target}: ${result.stderr || result.stdout}`);
  }
  return outDir;
}

/** Recursively search a directory tree for files containing a phrase. */
function findPhrase(dir, phrase) {
  if (!fs.existsSync(dir)) return false;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (findPhrase(abs, phrase)) return true;
    } else if (entry.isFile() && (entry.name.endsWith(".md") || entry.name.endsWith(".json") || entry.name.endsWith(".yaml") || entry.name.endsWith(".yml"))) {
      try {
        const content = fs.readFileSync(abs, "utf8");
        if (content.includes(phrase)) return true;
      } catch {
        // ignore unreadable files
      }
    }
  }
  return false;
}

before(() => {
  for (const target of TARGETS) {
    generated.set(target, generateTarget(target));
  }
});

after(() => {
  for (const dir of generated.values()) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

for (const target of TARGETS) {
  test(`dist/${target}: branch-pr Critical Rule 6 (branch-before-code) present`, () => {
    assert.ok(
      findPhrase(generated.get(target), BRANCH_PR_PHRASE),
      `generated ${target} target must contain '${BRANCH_PR_PHRASE}' — run scripts/configure to regenerate`
    );
  });

  test(`dist/${target}: orchestrator branch advisory present`, () => {
    assert.ok(
      findPhrase(generated.get(target), ORCHESTRATOR_PHRASE),
      `generated ${target} target must contain '${ORCHESTRATOR_PHRASE}' — run scripts/configure to regenerate`
    );
  });
}
